#!/usr/bin/python

from picamera2 import Picamera2
import numpy as np
import cv2

# Start picamera2
picam2 = Picamera2()
config = picam2.create_still_configuration(raw={'format':'SBGGR12'})
picam2.configure(config)
picam2.start()

# Grab a raw frame
raw = picam2.capture_array("raw").view(np.uint16)

# Convert to 16 bit
raw = raw*16

# Resize image for showing
result2 = cv2.resize(raw, dsize=(800,600), interpolation=cv2.INTER_CUBIC)
cv2.imshow('Output', result2)


# Debayer
cv2.waitKey()